const PROJECT_LIST = [
    { 
        id: 1, 
        url: "https://gme.healthquest.org/", 
        label: "gme.healthquest.org", 
        filter: "WordPress", 
        platform: "WordPress", 
        image: "/images/gme-healthquest-800x389.png",
        isFeatured: false,
    },
    { 
        id: 2, 
        url: "https://www.thinkdifferently.net/", 
        label: "thinkdifferently.net", 
        filter: "WordPress", 
        platform: "WordPress", 
        image: "/images/thinkdifferently.com-800x389.png",
        isFeatured: false,
    },
    { 
        id: 3, 
        url: "http://www.zarembabrown.com/", 
        label: "zarembabrown.com", 
        filter: "WordPress", 
        platform: "WordPress", 
        image: "/images/zarembabrown.com-800x389.png",
        isFeatured: false,
    },
    { 
        id: 4, 
        url: "http://www.westchesterbusinesscenter.com/", 
        label: "westchesterbusinesscenter.com", 
        filter: "Misc", 
        platform: "Business Catalyst", 
        image: "/images/westchesterbusinesscenter.com-800x389.png",
        isFeatured: false,
    },
    { 
        id: 5, 
        url: "http://thebonecompany.com/", 
        label: "thebonecompany.com", 
        filter: "WordPress", 
        platform: "WordPress", 
        image: "/images/thebonecompany.com-800x389.png",
        isFeatured: false,
    },
    { 
        id: 6, 
        url: "http://suburbanpest.com/", 
        label: "suburbanpest.com", 
        filter: "WordPress", 
        platform: "WordPress", 
        image: "/images/suburbanpest.com-800x389.png",
        isFeatured: false,
    },
    { 
        id: 7, 
        url: "http://www.1-800dogbone.com/", 
        label: "1-800dogbone.com", 
        filter: "WordPress", 
        platform: "WordPress", 
        image: "/images/1-800dogbone.com-800x389.png",
        isFeatured: false,
    },
    { 
        id: 8, 
        url: "http://www.ossiningchildrenscenter.org/", 
        label: "ossiningchildrenscenter.org", 
        filter: "Misc", 
        platform: "Business Catalyst", 
        image: "/images/ossiningchildrenscenter.org-800x389.png",
        isFeatured: false,
    },
    { 
        id: 9, 
        url: "hhttp://www.legaleaseinc.com/", 
        label: "legaleaseinc.com", 
        filter: "Misc", 
        platform: "Business Catalyst", 
        image: "/images/legaleaseinc.com-800x389.png",
        isFeatured: false,
    },
    { 
        id: 10, 
        url: "http://www.kelly-ip.com/", 
        label: "kelly-ip.com", 
        filter: "Misc", 
        platform: "Business Catalyst", 
        image: "/images/kelly-ip.com-800x389.png",
        isFeatured: false,
    },
    { 
        id: 11, 
        url: "http://www.climbleadership.com/", 
        label: "climbleadership.com", 
        filter: "Misc", 
        platform: "Business Catalyst", 
        image: "/images/climbleadership.com-800x389.png",
        isFeatured: false,
    },
    { 
        id: 12, 
        url: "http://www.mrluisamador.com/", 
        label: "mrluisamador.com", 
        filter: "Misc", 
        platform: "Nextjs", 
        image: "/images/mrluisamador.com.png",
        isFeatured: false,
    },
    {
        id: 13, 
        url: "https://la.bridgeprops.com/", 
        label: "la.bridgeprops.com", 
        filter: "Magento", 
        platform: "Magento 1", 
        image: "/images/bridgeprops.png",
        isFeatured: false,
    },
    { 
        id: 14, 
        url: "https://primitivesbykathy.com/", 
        label: "primitivesbykathy.com", 
        filter: "Magento", 
        platform: "Magento 1", 
        image: "/images/primitivesbykathy.png",
        isFeatured: false,
    },
    { 
        id: 15, 
        url: "https://www.organicpharmer.com/", 
        label: "organicpharmer.com", 
        filter: "Magento", 
        platform: "Magento 1", 
        image: "/images/organicpharmer.png",
        isFeatured: false,
    },
    { 
        id: 16, 
        url: "https://www.beautyplussalon.com/", 
        label: "beautyplussalon.com", 
        filter: "Magento", 
        platform: "Magento 1", 
        image: "/images/beautyplussalon.png",
        isFeatured: false,
    },
    { 
        id: 17, 
        url: "https://www.simoneperele.com/", 
        label: "simoneperele.com", 
        filter: "Magento", 
        platform: "Magento 1", 
        image: "/images/simoneperele.png",
        isFeatured: false,
    },
    { 
        id: 18, 
        url: "https://juliab.com/", 
        label: "juliab.com", 
        filter: "Magento", 
        platform: "Magento 2", 
        image: "/images/juliab.png",
        isFeatured: false,
    }
]

export default PROJECT_LIST;